import Head from 'next/head'
import Link from "next/link";


export default function Home() {
    return (
        <>
            <Head>
                <title>Karachi Real Est</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <>
                <>
                    {/*Nav Bar*/}
                    <nav className="nav collapsible">
                        <Link href="/">
                            <h1 className="nav__heading">KarachiRealEst</h1>
                        </Link>
                        <svg className="icon icon--white nav__toggler">
                            <use xlinkHref="/assets/sprite.svg#menu" />
                        </svg>
                        <ul className="list nav__list collapsible__content">
                            <li className="nav__item">
                                <Link href="/aboutus">About Us</Link>
                            </li>
                            <li className="nav__item">
                                <Link href="/ourvision">Our Vision</Link>
                            </li>
                            <li className="nav__item">
                                <Link href="/contactus">Contact Us</Link>
                            </li>
                        </ul>
                    </nav>
                    <>
                        <section className="contact-us">
                            <div className="container">
                                <div className="content">
                                    <h1>Contact Us</h1>
                                    <p>
                                        We’d love to hear from you! Whether you have a question, need
                                        assistance, or want to get started on your property journey, our team
                                        is here to help. Fill out the form below and we'll get back to you as
                                        soon as possible.
                                    </p>
                                    <form action="#" method="post" className="contact-form">
                                        <label htmlFor="name">Your Name</label>
                                        <input
                                            type="text"
                                            id="name"
                                            name="name"
                                            required=""
                                            placeholder="Enter your name"
                                        />
                                        <label htmlFor="email">Your Email</label>
                                        <input
                                            type="email"
                                            id="email"
                                            name="email"
                                            required=""
                                            placeholder="Enter your email address"
                                        />
                                        <label htmlFor="message">Your Message</label>
                                        <textarea
                                            id="message"
                                            name="message"
                                            rows={6}
                                            required=""
                                            placeholder="Enter your message"
                                            defaultValue={""}
                                        />
                                        <button type="submit">Send Message</button>
                                    </form>
                                </div>
                            </div>
                        </section>
                        {/* Footer */}
                        <footer className="footer">
                            <p className="footer-text">© KarachiRealEst 2024</p>
                        </footer>
                    </>

                </>

            </>

        </>
    )
}