import Head from 'next/head'
import Link from 'next/link'


export default function Home() {
    return (
        <>
            <Head>
                <title>Karachi Real Est</title>
                <meta name='description' content='Generated by create next app' />
                <meta name='viewport' content='width=device-width, initial-scale=1' />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <>
                {/*Nav Bar*/}
                <nav className="nav collapsible">
                    <Link href="/">
                        <h1 className="nav__heading">KarachiRealEst</h1>
                    </Link>
                    <svg className="icon icon--white nav__toggler">
                        <use xlinkHref="/assets/sprite.svg#menu" />
                    </svg>
                    <ul className="list nav__list collapsible__content">
                        <li className="nav__item">
                            <Link href="/aboutus">About Us</Link>
                        </li>
                        <li className="nav__item">
                            <Link href="/ourvision">Our Vision</Link>
                        </li>
                        <li className="nav__item">
                            <Link href="/contactus">Contact Us</Link>
                        </li>
                    </ul>
                </nav>
                <>
                    <section className="vision">
                        <div className="container">
                            <div className="content">
                                <h1>Our Vision</h1>
                                <p>
                                    At Karachi Real Estate, our vision is to revolutionize the real estate
                                    market in Karachi by offering unparalleled customer service,
                                    transparent transactions, and innovative property solutions. We aim to
                                    make every property journey seamless and stress-free for our clients,
                                    empowering them to make informed decisions with confidence.
                                </p>
                                <h2>What Drives Us</h2>
                                <p>
                                    We are driven by the belief that everyone deserves access to the right
                                    property, whether it's for personal or business needs. Our team is
                                    committed to providing reliable, professional, and efficient services
                                    to ensure that clients find not only a property but a place to build
                                    memories and grow.
                                </p>
                                <h2>Our Mission</h2>
                                <p>
                                    Our mission is simple: to be the most trusted and customer-centric
                                    real estate agency in Karachi. We aim to provide a comprehensive and
                                    dynamic range of real estate services that cater to every need. From
                                    buying and selling homes to finding the ideal commercial properties,
                                    we are here to guide our clients through every step of the journey,
                                    making the process clear and hassle-free.
                                </p>
                                <h2>Core Values</h2>
                                <ul>
                                    <li>
                                        <strong>Integrity:</strong> We uphold the highest standards of
                                        honesty and transparency in all our dealings, ensuring our clients
                                        feel secure and well-informed throughout the process.
                                    </li>
                                    <li>
                                        <strong>Customer-Centric:</strong> Our clients are at the heart of
                                        everything we do. We listen to their needs, provide expert advice,
                                        and deliver results tailored to their requirements.
                                    </li>
                                    <li>
                                        <strong>Innovation:</strong> We embrace new technologies and trends
                                        to offer innovative property solutions and market insights, helping
                                        our clients stay ahead in a rapidly evolving industry.
                                    </li>
                                    <li>
                                        <strong>Commitment to Excellence:</strong> We are committed to
                                        delivering high-quality service, ensuring that every transaction is
                                        executed with precision and professionalism.
                                    </li>
                                    <li>
                                        <strong>Community Focus:</strong> We believe in contributing to the
                                        growth and development of Karachi. Our success is tied to the
                                        success and prosperity of the local community.
                                    </li>
                                </ul>
                                <h2>Looking Ahead</h2>
                                <p>
                                    As we look to the future, we remain committed to expanding our
                                    portfolio, enhancing our services, and leveraging cutting-edge
                                    technologies to serve our clients better. Whether you're buying your
                                    first home, upgrading your office space, or investing in Karachi's
                                    dynamic property market, we want to be your first choice in real
                                    estate.
                                </p>
                                <p>
                                    We envision a Karachi where everyone has access to the property they
                                    need, and where every property transaction is a positive, empowering
                                    experience. Join us as we shape the future of real estate in Karachi.
                                </p>
                                <h2>Join Us in Our Journey</h2>
                                <p>
                                    If you share our passion for real estate and are looking for a place
                                    where values, innovation, and customer satisfaction come together, we
                                    invite you to partner with us. Whether you're a prospective buyer, a
                                    seller, or an investor, Karachi Real Estate offers a wide array of
                                    opportunities to help you reach your property goals.
                                </p>
                            </div>
                        </div>
                    </section>
                    {/* Footer */}
                    <footer className="footer">
                        <p className="footer-text">© KarachiRealEst 2024</p>
                    </footer>
                </>

            </>
        </>
    )
}